# Site settings
title:        "Dev Cho's blog"
description:  "Cho Hyunjun - currently work @ Samsung sds"
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "https://9Jun6.github.io" # the base hostname & protocol for your site
permalink:    /:year/:title
github:       "yourusername"
twitter:      "yourusername"
email:        "mail@example.com"
disqus-id:    "example" #leave blank if you dont want comments.

# Build settings
markdown:     kramdown
sass:
    style: :compressed
